### ISSUE TITLE
[Task] Update Clifford properties to new name

### ISSUE THREAD

**Issue by aclifford3** [aclifford3/hop-web#38]
The property `Confederate` is now called `United`.
The property `Palm Beach 462` is now called `Carmela`

* Update the property list in `hop-web` front-end application
* Update `hop.claims` DDB table user permissions.  This table determines which properties user have access to.  We need to ensure that users have permission to the newly named property.

**Comment by ludky** [comment]
- [ ] Add United and Carmela to user.claim table accordingly
- [ ] update property list in hop-web
- [ ] Delete Confederate and Palm Beach 462 once the new property permissions are verified at frontend

**Comment by ludky** [comment]
Assigned to Aleckiki for verification in dev.

**Comment by aclifford3** [comment]
Thanks for fixing this Fu!
